/**
 * Mean Keplerian elements for the simulated moons, referred to each parent
 * planet's equatorial plane at the epoch below.
 *
 * GENERATED by tools/calibrate-moons.mjs — do not edit by hand. Each row is
 * the average of osculating elements over one full orbital period of JPL
 * Horizons ephemeris, so the short-period wobbles cancel and the phase along
 * the orbit matches the real sky at the epoch.
 *
 * Earth's Moon is not in this table: solar perturbations are far too large for
 * a fixed ellipse, so ephemeris.ts propagates it with a truncated lunar series
 * instead.
 *
 * Deliberate approximations, all invisible at flight scale:
 *  - Node and apsidal precession from planetary oblateness are ignored, so the
 *    orbit's orientation slowly drifts away from reality over decades. The
 *    orbit's size, plane and period stay right.
 *  - Inner satellites' Laplace planes are treated as the parent's equator.
 *  - Mean motion comes from the tabulated sidereal period rather than mu/a^3.
 *
 * Reference epoch: 2026-07-29T00:00:00 TDB (t = 838555200 s past J2000).
 */

/** Seconds past J2000 at which the elements below are given. */
export const MOON_ELEMENTS_EPOCH = 838555200;

export interface MoonElements {
  id: string;
  parent: string;
  /** semi-major axis, m */
  a: number;
  /** eccentricity */
  e: number;
  /** inclination to the parent's equator, degrees (>90 means retrograde) */
  i: number;
  /** sidereal orbital period, days */
  periodDays: number;
  /** mean longitude at the epoch, degrees (= node + argPeri + meanAnomaly) */
  L: number;
  /** longitude of periapsis at the epoch, degrees (= node + argPeri) */
  lonPeri: number;
  /** longitude of the ascending node on the parent's equator, degrees */
  lonNode: number;
}

export const MOON_ELEMENTS: readonly MoonElements[] = [
  {
    id: 'phobos', parent: 'mars',
    a: 9378668.3, e: 0.0149995, i: 1.08649, periodDays: 0.31891023,
    L: 338.8773, lonPeri: 289.2356, lonNode: 259.7305,
  },
  {
    id: 'deimos', parent: 'mars',
    a: 23458541.4, e: 0.0002898, i: 2.66582, periodDays: 1.2624407,
    L: 217.3684, lonPeri: 78.4019, lonNode: 233.6891,
  },
  {
    id: 'io', parent: 'jupiter',
    a: 422028474.5, e: 0.0041568, i: 0.02651, periodDays: 1.7691378,
    L: 22.0334, lonPeri: 71.2473, lonNode: 54.5732,
  },
  {
    id: 'europa', parent: 'jupiter',
    a: 671258724.7, e: 0.0093294, i: 0.45538, periodDays: 3.551181,
    L: 226.7934, lonPeri: 252.4211, lonNode: 228.2574,
  },
  {
    id: 'ganymede', parent: 'jupiter',
    a: 1070609761.6, e: 0.0019766, i: 0.13686, periodDays: 7.154553,
    L: 59.3317, lonPeri: 1.1195, lonNode: 2.6466,
  },
  {
    id: 'callisto', parent: 'jupiter',
    a: 1883212164.8, e: 0.0072172, i: 0.26654, periodDays: 16.689018,
    L: 278.9874, lonPeri: 12.3249, lonNode: 167.3872,
  },
  {
    id: 'mimas', parent: 'saturn',
    a: 186019653.5, e: 0.0198208, i: 1.5769, periodDays: 0.9424218,
    L: 285.2396, lonPeri: 140.2323, lonNode: 192.6338,
  },
  {
    id: 'enceladus', parent: 'saturn',
    a: 238412546.7, e: 0.0047415, i: 0.00812, periodDays: 1.370218,
    L: 246.3552, lonPeri: 210.5474, lonNode: 228.0433,
  },
  {
    id: 'rhea', parent: 'saturn',
    a: 527235122.2, e: 0.0010093, i: 0.3055, periodDays: 4.5175,
    L: 203.9264, lonPeri: 213.1166, lonNode: 85.6966,
  },
  {
    id: 'titan', parent: 'saturn',
    a: 1221948760.4, e: 0.0287355, i: 0.40333, periodDays: 15.945421,
    L: 248.4168, lonPeri: 217.8683, lonNode: 250.7813,
  },
  {
    id: 'iapetus', parent: 'saturn',
    a: 3561810235.4, e: 0.0287953, i: 15.80316, periodDays: 79.330183,
    L: 213.0163, lonPeri: 243.6944, lonNode: 253.1202,
  },
  {
    id: 'titania', parent: 'uranus',
    a: 436280729.7, e: 0.0016117, i: 179.9592, periodDays: 8.7058717,
    L: 37.1689, lonPeri: 50.6541, lonNode: 359.7195,
  },
  {
    id: 'oberon', parent: 'uranus',
    a: 583503236.2, e: 0.0010747, i: 179.80614, periodDays: 13.4632389,
    L: 85.5209, lonPeri: 3.0886, lonNode: 336.469,
  },
  {
    id: 'triton', parent: 'neptune',
    a: 354692249.1, e: 0.0002068, i: 157.33332, periodDays: 5.876854,
    L: 76.5485, lonPeri: 299.905, lonNode: 191.6898,
  },
  {
    id: 'charon', parent: 'pluto',
    a: 19568262.9, e: 0.0014157, i: 0.08203, periodDays: 6.3872304,
    L: 130.6612, lonPeri: 145.908, lonNode: 11.1789,
  },
];

export const MOON_ELEMENTS_BY_ID: ReadonlyMap<string, MoonElements> = new Map(
  MOON_ELEMENTS.map((el) => [el.id, el]),
);
